# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'AnimeWave' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimeWave
	pod 'SwiftLint'
	pod 'SnapKit'
	pod 'Moya'
    pod 'SwiftGen'

    pod 'FirebaseAuth'
    pod 'FirebaseStorage'
    pod 'FirebaseFirestore'
end
